export const TRENDING_MOVIES = " TRENDING_MOVIES"

export const UPCOMING_MOVIES = 'UPCOMING_MOVIES'

export const TOP_RATED_MOVIES = 'TOP_RATED_MOVIES'

export const JOJO_MOVIES = 'JOJO_MOVIES'

export const NOW_SHOWING = 'NOW_SHOWING'

export const SEARCH_MOVIES = 'SEARCH_MOVIES'

export const LANDING_PAGE = 'LANDING_PAGE'



// THESE CONSTANST ARE USED TO CREATE LOGIN AND SIGN UP
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const GET_ERRORS = 'GET_ERRORS'

export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SIGN_USER_UP = 'SIGN_USER_UP'

export const USER_CREATED = 'USER_CREATED'

export const USERS_RECEIVED = 'USERS_RECEIVED'

// CONSTANTS FOR EMAIL
export const EMAIL_SEND = 'EMAIL_SEND'



